### ISSUE TITLE
Make a link to https://github.com/robertfeldt/BlackBoxOptim.jl

### ISSUE THREAD

**Issue by zaikunzhang** [libprima/PRIMA.jl#16]
In response to the kindness at https://github.com/robertfeldt/BlackBoxOptim.jl#blackboxoptimjl, I suggest we do something similar.

**Comment by emmt** [comment]
This is solved by commit 80ed3d904e7c137f1c4c7adecaaaf78dff06e827 when PR https://github.com/libprima/PRIMA.jl/pull/17/commits is merged.
